export const Menu = [
  {
    id: 1,
    name: "Chicken Biryani Hyderabadi",
    description: "Aromatic basmati rice with tender chicken, cooked with traditional spices and saffron",
    price: 350,
    originalPrice: 400,
    image: "/images/hero-food.jpeg",
    category: "Main Course",
    rating: 4.8,
    prepTime: "45 min",
    prepTimeMinutes: 45,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 3,
    isPopular: true,
    isVeg: false,
  },
  {
    id: 2,
    name: "Mutton Karahi Special",
    description: "Tender mutton cooked in traditional karahi with fresh tomatoes and aromatic spices",
    price: 450,
    originalPrice: 500,
    image: "/images/food-display.jpeg",
    category: "Main Course",
    rating: 4.9,
    prepTime: "60 min",
    prepTimeMinutes: 60,
    serves: "3-4 people",
    servingSize: "large",
    spiceLevel: 4,
    isPopular: true,
    isVeg: false,
  },
  {
    id: 3,
    name: "Chicken Tikka Masala",
    description: "Grilled chicken tikka in rich, creamy tomato-based curry sauce",
    price: 320,
    originalPrice: 370,
    image: "/images/menu-display.png",
    category: "Main Course",
    rating: 4.7,
    prepTime: "40 min",
    prepTimeMinutes: 40,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 3,
    isPopular: true,
    isVeg: false,
  },
  {
    id: 4,
    name: "Beef Pulao",
    description: "Fragrant rice dish with tender beef pieces and aromatic spices",
    price: 280,
    originalPrice: 320,
    image: "/images/hero-food.jpeg",
    category: "Rice Dishes",
    rating: 4.6,
    prepTime: "50 min",
    prepTimeMinutes: 50,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 2,
    isPopular: false,
    isVeg: false,
  },
  {
    id: 5,
    name: "Vegetable Biryani",
    description: "Aromatic basmati rice with mixed vegetables and traditional spices",
    price: 250,
    originalPrice: 290,
    image: "/images/food-display.jpeg",
    category: "Vegetarian",
    rating: 4.5,
    prepTime: "35 min",
    prepTimeMinutes: 35,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 2,
    isPopular: false,
    isVeg: true,
  },
  {
    id: 6,
    name: "Seekh Kebab",
    description: "Grilled minced meat kebabs with traditional spices and herbs",
    price: 180,
    originalPrice: 220,
    image: "/images/menu-display.png",
    category: "Appetizers",
    rating: 4.8,
    prepTime: "25 min",
    prepTimeMinutes: 25,
    serves: "1-2 people",
    servingSize: "small",
    spiceLevel: 3,
    isPopular: true,
    isVeg: false,
  },
  {
    id: 7,
    name: "Chicken Korma",
    description: "Mild and creamy chicken curry with cashews and aromatic spices",
    price: 300,
    originalPrice: 340,
    image: "/images/hero-food.jpeg",
    category: "Main Course",
    rating: 4.6,
    prepTime: "45 min",
    prepTimeMinutes: 45,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 1,
    isPopular: false,
    isVeg: false,
  },
  {
    id: 8,
    name: "Dal Makhani",
    description: "Rich and creamy black lentils cooked with butter and cream",
    price: 200,
    originalPrice: 240,
    image: "/images/food-display.jpeg",
    category: "Vegetarian",
    rating: 4.7,
    prepTime: "30 min",
    prepTimeMinutes: 30,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 1,
    isPopular: true,
    isVeg: true,
  },
  {
    id: 9,
    name: "Fish Curry",
    description: "Fresh fish cooked in spicy coconut curry with traditional spices",
    price: 380,
    originalPrice: 420,
    image: "/images/menu-display.png",
    category: "Seafood",
    rating: 4.5,
    prepTime: "35 min",
    prepTimeMinutes: 35,
    serves: "2-3 people",
    servingSize: "medium",
    spiceLevel: 4,
    isPopular: false,
    isVeg: false,
  },
  {
    id: 10,
    name: "Gulab Jamun",
    description: "Traditional sweet dumplings in sugar syrup, served warm",
    price: 80,
    originalPrice: 100,
    image: "/images/hero-food.jpeg",
    category: "Desserts",
    rating: 4.9,
    prepTime: "15 min",
    prepTimeMinutes: 15,
    serves: "1-2 people",
    servingSize: "small",
    spiceLevel: 0,
    isPopular: true,
    isVeg: true,
  },
  {
    id: 11,
    name: "Chicken Shawarma",
    description: "Marinated chicken wrapped in pita bread with vegetables and sauce",
    price: 220,
    originalPrice: 260,
    image: "/images/food-display.jpeg",
    category: "Fast Food",
    rating: 4.4,
    prepTime: "20 min",
    prepTimeMinutes: 20,
    serves: "1 person",
    servingSize: "small",
    spiceLevel: 2,
    isPopular: false,
    isVeg: false,
  },
  {
    id: 12,
    name: "Paneer Tikka",
    description: "Grilled cottage cheese cubes marinated in spices and yogurt",
    price: 240,
    originalPrice: 280,
    image: "/images/menu-display.png",
    category: "Vegetarian",
    rating: 4.6,
    prepTime: "30 min",
    prepTimeMinutes: 30,
    serves: "1-2 people",
    servingSize: "small",
    spiceLevel: 2,
    isPopular: true,
    isVeg: true,
  },
]

export const MenuCategories = [
  "All",
  "Main Course",
  "Rice Dishes",
  "Vegetarian",
  "Appetizers",
  "Seafood",
  "Desserts",
  "Fast Food",
]

export const SpiceLevels = [
  { value: "all", label: "All Spice Levels", level: null },
  { value: "mild", label: "Mild (0-1)", level: [0, 1] },
  { value: "medium", label: "Medium (2-3)", level: [2, 3] },
  { value: "hot", label: "Hot (4-5)", level: [4, 5] },
]

export const PrepTimeRanges = [
  { value: "all", label: "Any Time", range: null },
  { value: "quick", label: "Quick (≤20 min)", range: [0, 20] },
  { value: "medium", label: "Medium (21-40 min)", range: [21, 40] },
  { value: "slow", label: "Takes Time (>40 min)", range: [41, 120] },
]

export const ServingSizes = [
  { value: "all", label: "All Sizes" },
  { value: "small", label: "Individual (1-2)" },
  { value: "medium", label: "Small Group (2-3)" },
  { value: "large", label: "Large Group (3+)" },
]

export type MenuItem = {
  id: number
  name: string
  description: string
  price: number
  originalPrice?: number
  image: string
  category: string
  rating: number
  prepTime: string
  prepTimeMinutes: number
  serves: string
  servingSize: "small" | "medium" | "large"
  spiceLevel: number
  isPopular: boolean
  isVeg: boolean
}
